### ISSUE TITLE
更换为最新版Slimefun-f30bdf2-canary粘液科技核心，无法正常加载该插件

### ISSUE THREAD

**Issue by aesopcmc** [GuizhanCraft/FoxyMachines-CN#22]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/FoxyMachines/issues)，且没有找到相同的问题

### 问题描述

paper版本： 1.19.3

更换为最新版Slimefun-f30bdf2-canary粘液科技核心，无法正常加载该插件。启动期间报警告：：

[00:53:09 INFO]: [FoxyMachines] Enabling FoxyMachines vBuild 22 zh-CN(ybw0014) (git fb4eeb7)
[00:53:09 WARN]: org.yaml.snakeyaml.emitter.EmitterException: expected NodeEvent, but got <org.yaml.snakeyaml.events.CommentEvent(type=IN_LINE, value= 8)>
[00:53:09 WARN]:        at org.yaml.snakeyaml.emitter.Emitter.expectNode(Emitter.java:492)
[00:53:09 WARN]:        at org.yaml.snakeyaml.emitter.Emitter.access$1800(Emitter.java:68)
[00:53:09 WARN]:        at org.yaml.snakeyaml.emitter.Emitter$ExpectBlockMappingKey.expect(Emitter.java:780)
[00:53:09 WARN]:        at org.yaml.snakeyaml.emitter.Emitter.emit(Emitter.java:270)
[00:53:09 WARN]:        at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:174)
[00:53:09 WARN]:        at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:205)
[00:53:09 WARN]:        at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:113)
[00:53:09 WARN]:        at org.yaml.snakeyaml.Yaml.serialize(Yaml.java:355)
[00:53:09 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:91)
[00:53:09 WARN]:        at [粘液科技扩展-神秘科技]FoxyMachines-Build 22 zh-CN(ybw0014) (git fb4eeb7).jar//me.gallowsdove.foxymachines.infinitylib.core.AddonConfig.saveToString(AddonConfig.java:114)
[00:53:09 WARN]:        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65)
[00:53:09 WARN]:        at [粘液科技扩展-神秘科技]FoxyMachines-Build 22 zh-CN(ybw0014) (git fb4eeb7).jar//me.gallowsdove.foxymachines.infinitylib.core.AddonConfig.save(AddonConfig.java:77)
[00:53:09 WARN]:        at [粘液科技扩展-神秘科技]FoxyMachines-Build 22 zh-CN(ybw0014) (git fb4eeb7).jar//me.gallowsdove.foxymachines.infinitylib.core.AddonConfig.save(AddonConfig.java:67)
[00:53:09 WARN]:        at [粘液科技扩展-神秘科技]FoxyMachines-Build 22 zh-CN(ybw0014) (git fb4eeb7).jar//me.gallowsdove.foxymachines.infinitylib.core.AddonConfig.reload(AddonConfig.java:90)
[00:53:09 WARN]:        at [粘液科技扩展-神秘科技]FoxyMachines-Build 22 zh-CN(ybw0014) (git fb4eeb7).jar//me.gallowsdove.foxymachines.infinitylib.core.AddonConfig.loadDefaults(AddonConfig.java:155)
[00:53:09 WARN]:        at [粘液科技扩展-神秘科技]FoxyMachines-Build 22 zh-CN(ybw0014) (git fb4eeb7).jar//me.gallowsdove.foxymachines.infinitylib.core.AddonConfig.<init>(AddonConfig.java:35)
[00:53:09 WARN]:        at [粘液科技扩展-神秘科技]FoxyMachines-Build 22 zh-CN(ybw0014) (git fb4eeb7).jar//me.gallowsdove.foxymachines.infinitylib.core.AbstractAddon.onEnable(AbstractAddon.java:151)
[00:53:09 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:53:09 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
[00:53:09 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544)
[00:53:09 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578)
[00:53:09 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492)
[00:53:09 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[00:53:09 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[00:53:09 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:301)
[00:53:09 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[00:53:09 WARN]: java.lang.NullPointerException: Cannot invoke "me.gallowsdove.foxymachines.infinitylib.core.AddonConfig.getBoolean(String)" because the return value of "me.gallowsdove.foxymachines.FoxyMachines.getConfig()" is null
[00:53:09 WARN]:        at [粘液科技扩展-神秘科技]FoxyMachines-Build 22 zh-CN(ybw0014) (git fb4eeb7).jar//me.gallowsdove.foxymachines.FoxyMachines.enable(FoxyMachines.java:48)
[00:53:09 WARN]:        at [粘液科技扩展-神秘科技]FoxyMachines-Build 22 zh-CN(ybw0014) (git fb4eeb7).jar//me.gallowsdove.foxymachines.infinitylib.core.AbstractAddon.onEnable(AbstractAddon.java:194)
[00:53:09 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:53:09 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
[00:53:09 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544)
[00:53:09 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578)
[00:53:09 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492)
[00:53:09 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[00:53:09 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[00:53:09 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:301)
[00:53:09 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)

### 复现步骤

启动程序

### 预期行为

正常加载

### 服务端软件

Spigot

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Slimefun-f30bdf2-canary.jar

### 插件版本

FoxyMachines-Build 22 zh-CN(ybw0014)

**Comment by ybw0014** [comment]
尝试删除`config.yml`重新生成
